// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/wsjava/signaling/wsjava.proto

package wsjava.signaling.pbsws;

public final class Wsjava {
  private Wsjava() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code wsjava.signaling.pbsws.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Default = 0;</code>
     */
    Default(0),
    /**
     * <code>LocalId = 1;</code>
     */
    LocalId(1),
    /**
     * <code>Peers = 2;</code>
     */
    Peers(2),
    /**
     * <code>Offer = 3;</code>
     */
    Offer(3),
    /**
     * <code>Answer = 4;</code>
     */
    Answer(4),
    /**
     * <code>IceCandidate = 5;</code>
     */
    IceCandidate(5),
    /**
     * <code>Error = 6;</code>
     */
    Error(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Default = 0;</code>
     */
    public static final int Default_VALUE = 0;
    /**
     * <code>LocalId = 1;</code>
     */
    public static final int LocalId_VALUE = 1;
    /**
     * <code>Peers = 2;</code>
     */
    public static final int Peers_VALUE = 2;
    /**
     * <code>Offer = 3;</code>
     */
    public static final int Offer_VALUE = 3;
    /**
     * <code>Answer = 4;</code>
     */
    public static final int Answer_VALUE = 4;
    /**
     * <code>IceCandidate = 5;</code>
     */
    public static final int IceCandidate_VALUE = 5;
    /**
     * <code>Error = 6;</code>
     */
    public static final int Error_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return Default;
        case 1: return LocalId;
        case 2: return Peers;
        case 3: return Offer;
        case 4: return Answer;
        case 5: return IceCandidate;
        case 6: return Error;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return wsjava.signaling.pbsws.Wsjava.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:wsjava.signaling.pbsws.DataType)
  }

  public interface MessageObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wsjava.signaling.pbsws.MessageObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
     * @return The dataType.
     */
    wsjava.signaling.pbsws.Wsjava.DataType getDataType();

    /**
     * <code>repeated string listData = 2;</code>
     * @return A list containing the listData.
     */
    java.util.List<java.lang.String>
        getListDataList();
    /**
     * <code>repeated string listData = 2;</code>
     * @return The count of listData.
     */
    int getListDataCount();
    /**
     * <code>repeated string listData = 2;</code>
     * @param index The index of the element to return.
     * @return The listData at the given index.
     */
    java.lang.String getListData(int index);
    /**
     * <code>repeated string listData = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the listData at the given index.
     */
    com.google.protobuf.ByteString
        getListDataBytes(int index);

    /**
     * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
     * @return Whether the stringDataObject field is set.
     */
    boolean hasStringDataObject();
    /**
     * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
     * @return The stringDataObject.
     */
    wsjava.signaling.pbsws.Wsjava.StringDataObject getStringDataObject();
    /**
     * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
     */
    wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder getStringDataObjectOrBuilder();

    /**
     * <code>string stringData = 4;</code>
     * @return The stringData.
     */
    java.lang.String getStringData();
    /**
     * <code>string stringData = 4;</code>
     * @return The bytes for stringData.
     */
    com.google.protobuf.ByteString
        getStringDataBytes();

    /**
     * <code>string log = 5;</code>
     * @return The log.
     */
    java.lang.String getLog();
    /**
     * <code>string log = 5;</code>
     * @return The bytes for log.
     */
    com.google.protobuf.ByteString
        getLogBytes();

    /**
     * <code>string timeStamp = 6;</code>
     * @return The timeStamp.
     */
    java.lang.String getTimeStamp();
    /**
     * <code>string timeStamp = 6;</code>
     * @return The bytes for timeStamp.
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();
  }
  /**
   * Protobuf type {@code wsjava.signaling.pbsws.MessageObject}
   */
  public static final class MessageObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wsjava.signaling.pbsws.MessageObject)
      MessageObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageObject.newBuilder() to construct.
    private MessageObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageObject() {
      dataType_ = 0;
      listData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      stringData_ = "";
      log_ = "";
      timeStamp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_MessageObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_MessageObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wsjava.signaling.pbsws.Wsjava.MessageObject.class, wsjava.signaling.pbsws.Wsjava.MessageObject.Builder.class);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_ = 0;
    /**
     * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public wsjava.signaling.pbsws.Wsjava.DataType getDataType() {
      wsjava.signaling.pbsws.Wsjava.DataType result = wsjava.signaling.pbsws.Wsjava.DataType.forNumber(dataType_);
      return result == null ? wsjava.signaling.pbsws.Wsjava.DataType.UNRECOGNIZED : result;
    }

    public static final int LISTDATA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList listData_;
    /**
     * <code>repeated string listData = 2;</code>
     * @return A list containing the listData.
     */
    public com.google.protobuf.ProtocolStringList
        getListDataList() {
      return listData_;
    }
    /**
     * <code>repeated string listData = 2;</code>
     * @return The count of listData.
     */
    public int getListDataCount() {
      return listData_.size();
    }
    /**
     * <code>repeated string listData = 2;</code>
     * @param index The index of the element to return.
     * @return The listData at the given index.
     */
    public java.lang.String getListData(int index) {
      return listData_.get(index);
    }
    /**
     * <code>repeated string listData = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the listData at the given index.
     */
    public com.google.protobuf.ByteString
        getListDataBytes(int index) {
      return listData_.getByteString(index);
    }

    public static final int STRINGDATAOBJECT_FIELD_NUMBER = 3;
    private wsjava.signaling.pbsws.Wsjava.StringDataObject stringDataObject_;
    /**
     * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
     * @return Whether the stringDataObject field is set.
     */
    @java.lang.Override
    public boolean hasStringDataObject() {
      return stringDataObject_ != null;
    }
    /**
     * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
     * @return The stringDataObject.
     */
    @java.lang.Override
    public wsjava.signaling.pbsws.Wsjava.StringDataObject getStringDataObject() {
      return stringDataObject_ == null ? wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance() : stringDataObject_;
    }
    /**
     * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
     */
    @java.lang.Override
    public wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder getStringDataObjectOrBuilder() {
      return stringDataObject_ == null ? wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance() : stringDataObject_;
    }

    public static final int STRINGDATA_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stringData_ = "";
    /**
     * <code>string stringData = 4;</code>
     * @return The stringData.
     */
    @java.lang.Override
    public java.lang.String getStringData() {
      java.lang.Object ref = stringData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringData_ = s;
        return s;
      }
    }
    /**
     * <code>string stringData = 4;</code>
     * @return The bytes for stringData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringDataBytes() {
      java.lang.Object ref = stringData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOG_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object log_ = "";
    /**
     * <code>string log = 5;</code>
     * @return The log.
     */
    @java.lang.Override
    public java.lang.String getLog() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        log_ = s;
        return s;
      }
    }
    /**
     * <code>string log = 5;</code>
     * @return The bytes for log.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timeStamp_ = "";
    /**
     * <code>string timeStamp = 6;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timeStamp = 6;</code>
     * @return The bytes for timeStamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != wsjava.signaling.pbsws.Wsjava.DataType.Default.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      for (int i = 0; i < listData_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, listData_.getRaw(i));
      }
      if (stringDataObject_ != null) {
        output.writeMessage(3, getStringDataObject());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringData_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stringData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(log_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, log_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStamp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, timeStamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != wsjava.signaling.pbsws.Wsjava.DataType.Default.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < listData_.size(); i++) {
          dataSize += computeStringSizeNoTag(listData_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getListDataList().size();
      }
      if (stringDataObject_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStringDataObject());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringData_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stringData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(log_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, log_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStamp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, timeStamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wsjava.signaling.pbsws.Wsjava.MessageObject)) {
        return super.equals(obj);
      }
      wsjava.signaling.pbsws.Wsjava.MessageObject other = (wsjava.signaling.pbsws.Wsjava.MessageObject) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getListDataList()
          .equals(other.getListDataList())) return false;
      if (hasStringDataObject() != other.hasStringDataObject()) return false;
      if (hasStringDataObject()) {
        if (!getStringDataObject()
            .equals(other.getStringDataObject())) return false;
      }
      if (!getStringData()
          .equals(other.getStringData())) return false;
      if (!getLog()
          .equals(other.getLog())) return false;
      if (!getTimeStamp()
          .equals(other.getTimeStamp())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      if (getListDataCount() > 0) {
        hash = (37 * hash) + LISTDATA_FIELD_NUMBER;
        hash = (53 * hash) + getListDataList().hashCode();
      }
      if (hasStringDataObject()) {
        hash = (37 * hash) + STRINGDATAOBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getStringDataObject().hashCode();
      }
      hash = (37 * hash) + STRINGDATA_FIELD_NUMBER;
      hash = (53 * hash) + getStringData().hashCode();
      hash = (37 * hash) + LOG_FIELD_NUMBER;
      hash = (53 * hash) + getLog().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wsjava.signaling.pbsws.Wsjava.MessageObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wsjava.signaling.pbsws.Wsjava.MessageObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wsjava.signaling.pbsws.MessageObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wsjava.signaling.pbsws.MessageObject)
        wsjava.signaling.pbsws.Wsjava.MessageObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_MessageObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_MessageObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wsjava.signaling.pbsws.Wsjava.MessageObject.class, wsjava.signaling.pbsws.Wsjava.MessageObject.Builder.class);
      }

      // Construct using wsjava.signaling.pbsws.Wsjava.MessageObject.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dataType_ = 0;
        listData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        stringDataObject_ = null;
        if (stringDataObjectBuilder_ != null) {
          stringDataObjectBuilder_.dispose();
          stringDataObjectBuilder_ = null;
        }
        stringData_ = "";
        log_ = "";
        timeStamp_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_MessageObject_descriptor;
      }

      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.MessageObject getDefaultInstanceForType() {
        return wsjava.signaling.pbsws.Wsjava.MessageObject.getDefaultInstance();
      }

      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.MessageObject build() {
        wsjava.signaling.pbsws.Wsjava.MessageObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.MessageObject buildPartial() {
        wsjava.signaling.pbsws.Wsjava.MessageObject result = new wsjava.signaling.pbsws.Wsjava.MessageObject(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(wsjava.signaling.pbsws.Wsjava.MessageObject result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          listData_ = listData_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.listData_ = listData_;
      }

      private void buildPartial0(wsjava.signaling.pbsws.Wsjava.MessageObject result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dataType_ = dataType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.stringDataObject_ = stringDataObjectBuilder_ == null
              ? stringDataObject_
              : stringDataObjectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.stringData_ = stringData_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.log_ = log_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timeStamp_ = timeStamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wsjava.signaling.pbsws.Wsjava.MessageObject) {
          return mergeFrom((wsjava.signaling.pbsws.Wsjava.MessageObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wsjava.signaling.pbsws.Wsjava.MessageObject other) {
        if (other == wsjava.signaling.pbsws.Wsjava.MessageObject.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (!other.listData_.isEmpty()) {
          if (listData_.isEmpty()) {
            listData_ = other.listData_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureListDataIsMutable();
            listData_.addAll(other.listData_);
          }
          onChanged();
        }
        if (other.hasStringDataObject()) {
          mergeStringDataObject(other.getStringDataObject());
        }
        if (!other.getStringData().isEmpty()) {
          stringData_ = other.stringData_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getLog().isEmpty()) {
          log_ = other.log_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                dataType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureListDataIsMutable();
                listData_.add(s);
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getStringDataObjectFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                stringData_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                log_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                timeStamp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int dataType_ = 0;
      /**
       * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.DataType getDataType() {
        wsjava.signaling.pbsws.Wsjava.DataType result = wsjava.signaling.pbsws.Wsjava.DataType.forNumber(dataType_);
        return result == null ? wsjava.signaling.pbsws.Wsjava.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(wsjava.signaling.pbsws.Wsjava.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.wsjava.signaling.pbsws.DataType dataType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList listData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListDataIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          listData_ = new com.google.protobuf.LazyStringArrayList(listData_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @return A list containing the listData.
       */
      public com.google.protobuf.ProtocolStringList
          getListDataList() {
        return listData_.getUnmodifiableView();
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @return The count of listData.
       */
      public int getListDataCount() {
        return listData_.size();
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @param index The index of the element to return.
       * @return The listData at the given index.
       */
      public java.lang.String getListData(int index) {
        return listData_.get(index);
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the listData at the given index.
       */
      public com.google.protobuf.ByteString
          getListDataBytes(int index) {
        return listData_.getByteString(index);
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @param index The index to set the value at.
       * @param value The listData to set.
       * @return This builder for chaining.
       */
      public Builder setListData(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureListDataIsMutable();
        listData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @param value The listData to add.
       * @return This builder for chaining.
       */
      public Builder addListData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureListDataIsMutable();
        listData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @param values The listData to add.
       * @return This builder for chaining.
       */
      public Builder addAllListData(
          java.lang.Iterable<java.lang.String> values) {
        ensureListDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearListData() {
        listData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listData = 2;</code>
       * @param value The bytes of the listData to add.
       * @return This builder for chaining.
       */
      public Builder addListDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureListDataIsMutable();
        listData_.add(value);
        onChanged();
        return this;
      }

      private wsjava.signaling.pbsws.Wsjava.StringDataObject stringDataObject_;
      private com.google.protobuf.SingleFieldBuilderV3<
          wsjava.signaling.pbsws.Wsjava.StringDataObject, wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder, wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder> stringDataObjectBuilder_;
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       * @return Whether the stringDataObject field is set.
       */
      public boolean hasStringDataObject() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       * @return The stringDataObject.
       */
      public wsjava.signaling.pbsws.Wsjava.StringDataObject getStringDataObject() {
        if (stringDataObjectBuilder_ == null) {
          return stringDataObject_ == null ? wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance() : stringDataObject_;
        } else {
          return stringDataObjectBuilder_.getMessage();
        }
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      public Builder setStringDataObject(wsjava.signaling.pbsws.Wsjava.StringDataObject value) {
        if (stringDataObjectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringDataObject_ = value;
        } else {
          stringDataObjectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      public Builder setStringDataObject(
          wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder builderForValue) {
        if (stringDataObjectBuilder_ == null) {
          stringDataObject_ = builderForValue.build();
        } else {
          stringDataObjectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      public Builder mergeStringDataObject(wsjava.signaling.pbsws.Wsjava.StringDataObject value) {
        if (stringDataObjectBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            stringDataObject_ != null &&
            stringDataObject_ != wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance()) {
            getStringDataObjectBuilder().mergeFrom(value);
          } else {
            stringDataObject_ = value;
          }
        } else {
          stringDataObjectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      public Builder clearStringDataObject() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stringDataObject_ = null;
        if (stringDataObjectBuilder_ != null) {
          stringDataObjectBuilder_.dispose();
          stringDataObjectBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      public wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder getStringDataObjectBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getStringDataObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      public wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder getStringDataObjectOrBuilder() {
        if (stringDataObjectBuilder_ != null) {
          return stringDataObjectBuilder_.getMessageOrBuilder();
        } else {
          return stringDataObject_ == null ?
              wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance() : stringDataObject_;
        }
      }
      /**
       * <code>.wsjava.signaling.pbsws.StringDataObject stringDataObject = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          wsjava.signaling.pbsws.Wsjava.StringDataObject, wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder, wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder> 
          getStringDataObjectFieldBuilder() {
        if (stringDataObjectBuilder_ == null) {
          stringDataObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              wsjava.signaling.pbsws.Wsjava.StringDataObject, wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder, wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder>(
                  getStringDataObject(),
                  getParentForChildren(),
                  isClean());
          stringDataObject_ = null;
        }
        return stringDataObjectBuilder_;
      }

      private java.lang.Object stringData_ = "";
      /**
       * <code>string stringData = 4;</code>
       * @return The stringData.
       */
      public java.lang.String getStringData() {
        java.lang.Object ref = stringData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringData = 4;</code>
       * @return The bytes for stringData.
       */
      public com.google.protobuf.ByteString
          getStringDataBytes() {
        java.lang.Object ref = stringData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringData = 4;</code>
       * @param value The stringData to set.
       * @return This builder for chaining.
       */
      public Builder setStringData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stringData_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string stringData = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringData() {
        stringData_ = getDefaultInstance().getStringData();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string stringData = 4;</code>
       * @param value The bytes for stringData to set.
       * @return This builder for chaining.
       */
      public Builder setStringDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stringData_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object log_ = "";
      /**
       * <code>string log = 5;</code>
       * @return The log.
       */
      public java.lang.String getLog() {
        java.lang.Object ref = log_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          log_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string log = 5;</code>
       * @return The bytes for log.
       */
      public com.google.protobuf.ByteString
          getLogBytes() {
        java.lang.Object ref = log_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          log_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string log = 5;</code>
       * @param value The log to set.
       * @return This builder for chaining.
       */
      public Builder setLog(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        log_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string log = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLog() {
        log_ = getDefaultInstance().getLog();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string log = 5;</code>
       * @param value The bytes for log to set.
       * @return This builder for chaining.
       */
      public Builder setLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        log_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>string timeStamp = 6;</code>
       * @return The timeStamp.
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timeStamp = 6;</code>
       * @return The bytes for timeStamp.
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timeStamp = 6;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timeStamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        timeStamp_ = getDefaultInstance().getTimeStamp();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamp = 6;</code>
       * @param value The bytes for timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timeStamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wsjava.signaling.pbsws.MessageObject)
    }

    // @@protoc_insertion_point(class_scope:wsjava.signaling.pbsws.MessageObject)
    private static final wsjava.signaling.pbsws.Wsjava.MessageObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wsjava.signaling.pbsws.Wsjava.MessageObject();
    }

    public static wsjava.signaling.pbsws.Wsjava.MessageObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageObject>
        PARSER = new com.google.protobuf.AbstractParser<MessageObject>() {
      @java.lang.Override
      public MessageObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wsjava.signaling.pbsws.Wsjava.MessageObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StringDataObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wsjava.signaling.pbsws.StringDataObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string from = 1;</code>
     * @return The from.
     */
    java.lang.String getFrom();
    /**
     * <code>string from = 1;</code>
     * @return The bytes for from.
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>string to = 2;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>string offer = 3;</code>
     * @return The offer.
     */
    java.lang.String getOffer();
    /**
     * <code>string offer = 3;</code>
     * @return The bytes for offer.
     */
    com.google.protobuf.ByteString
        getOfferBytes();
  }
  /**
   * Protobuf type {@code wsjava.signaling.pbsws.StringDataObject}
   */
  public static final class StringDataObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wsjava.signaling.pbsws.StringDataObject)
      StringDataObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StringDataObject.newBuilder() to construct.
    private StringDataObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StringDataObject() {
      from_ = "";
      to_ = "";
      offer_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StringDataObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_StringDataObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_StringDataObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wsjava.signaling.pbsws.Wsjava.StringDataObject.class, wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object from_ = "";
    /**
     * <code>string from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <code>string from = 1;</code>
     * @return The bytes for from.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object to_ = "";
    /**
     * <code>string to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object offer_ = "";
    /**
     * <code>string offer = 3;</code>
     * @return The offer.
     */
    @java.lang.Override
    public java.lang.String getOffer() {
      java.lang.Object ref = offer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        offer_ = s;
        return s;
      }
    }
    /**
     * <code>string offer = 3;</code>
     * @return The bytes for offer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOfferBytes() {
      java.lang.Object ref = offer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        offer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, from_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(offer_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, offer_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, from_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(offer_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, offer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wsjava.signaling.pbsws.Wsjava.StringDataObject)) {
        return super.equals(obj);
      }
      wsjava.signaling.pbsws.Wsjava.StringDataObject other = (wsjava.signaling.pbsws.Wsjava.StringDataObject) obj;

      if (!getFrom()
          .equals(other.getFrom())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getOffer()
          .equals(other.getOffer())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + OFFER_FIELD_NUMBER;
      hash = (53 * hash) + getOffer().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wsjava.signaling.pbsws.Wsjava.StringDataObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wsjava.signaling.pbsws.Wsjava.StringDataObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wsjava.signaling.pbsws.StringDataObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wsjava.signaling.pbsws.StringDataObject)
        wsjava.signaling.pbsws.Wsjava.StringDataObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_StringDataObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_StringDataObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wsjava.signaling.pbsws.Wsjava.StringDataObject.class, wsjava.signaling.pbsws.Wsjava.StringDataObject.Builder.class);
      }

      // Construct using wsjava.signaling.pbsws.Wsjava.StringDataObject.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        from_ = "";
        to_ = "";
        offer_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wsjava.signaling.pbsws.Wsjava.internal_static_wsjava_signaling_pbsws_StringDataObject_descriptor;
      }

      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.StringDataObject getDefaultInstanceForType() {
        return wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance();
      }

      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.StringDataObject build() {
        wsjava.signaling.pbsws.Wsjava.StringDataObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wsjava.signaling.pbsws.Wsjava.StringDataObject buildPartial() {
        wsjava.signaling.pbsws.Wsjava.StringDataObject result = new wsjava.signaling.pbsws.Wsjava.StringDataObject(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(wsjava.signaling.pbsws.Wsjava.StringDataObject result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.from_ = from_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.to_ = to_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.offer_ = offer_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wsjava.signaling.pbsws.Wsjava.StringDataObject) {
          return mergeFrom((wsjava.signaling.pbsws.Wsjava.StringDataObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wsjava.signaling.pbsws.Wsjava.StringDataObject other) {
        if (other == wsjava.signaling.pbsws.Wsjava.StringDataObject.getDefaultInstance()) return this;
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getOffer().isEmpty()) {
          offer_ = other.offer_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                from_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                to_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                offer_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object from_ = "";
      /**
       * <code>string from = 1;</code>
       * @return The from.
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string from = 1;</code>
       * @return The bytes for from.
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from = 1;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        from_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string from = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        from_ = getDefaultInstance().getFrom();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string from = 1;</code>
       * @param value The bytes for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        from_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 2;</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 2;</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        to_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        to_ = getDefaultInstance().getTo();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string to = 2;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        to_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object offer_ = "";
      /**
       * <code>string offer = 3;</code>
       * @return The offer.
       */
      public java.lang.String getOffer() {
        java.lang.Object ref = offer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          offer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string offer = 3;</code>
       * @return The bytes for offer.
       */
      public com.google.protobuf.ByteString
          getOfferBytes() {
        java.lang.Object ref = offer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          offer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string offer = 3;</code>
       * @param value The offer to set.
       * @return This builder for chaining.
       */
      public Builder setOffer(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        offer_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string offer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffer() {
        offer_ = getDefaultInstance().getOffer();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string offer = 3;</code>
       * @param value The bytes for offer to set.
       * @return This builder for chaining.
       */
      public Builder setOfferBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        offer_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wsjava.signaling.pbsws.StringDataObject)
    }

    // @@protoc_insertion_point(class_scope:wsjava.signaling.pbsws.StringDataObject)
    private static final wsjava.signaling.pbsws.Wsjava.StringDataObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wsjava.signaling.pbsws.Wsjava.StringDataObject();
    }

    public static wsjava.signaling.pbsws.Wsjava.StringDataObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringDataObject>
        PARSER = new com.google.protobuf.AbstractParser<StringDataObject>() {
      @java.lang.Override
      public StringDataObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StringDataObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringDataObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wsjava.signaling.pbsws.Wsjava.StringDataObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wsjava_signaling_pbsws_MessageObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wsjava_signaling_pbsws_MessageObject_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wsjava_signaling_pbsws_StringDataObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wsjava_signaling_pbsws_StringDataObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+src/main/java/wsjava/signaling/wsjava." +
      "proto\022\026wsjava.signaling.pbsws\"\315\001\n\rMessag" +
      "eObject\0222\n\010dataType\030\001 \001(\0162 .wsjava.signa" +
      "ling.pbsws.DataType\022\020\n\010listData\030\002 \003(\t\022B\n" +
      "\020stringDataObject\030\003 \001(\0132(.wsjava.signali" +
      "ng.pbsws.StringDataObject\022\022\n\nstringData\030" +
      "\004 \001(\t\022\013\n\003log\030\005 \001(\t\022\021\n\ttimeStamp\030\006 \001(\t\";\n" +
      "\020StringDataObject\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 " +
      "\001(\t\022\r\n\005offer\030\003 \001(\t*c\n\010DataType\022\013\n\007Defaul" +
      "t\020\000\022\013\n\007LocalId\020\001\022\t\n\005Peers\020\002\022\t\n\005Offer\020\003\022\n" +
      "\n\006Answer\020\004\022\020\n\014IceCandidate\020\005\022\t\n\005Error\020\006b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wsjava_signaling_pbsws_MessageObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wsjava_signaling_pbsws_MessageObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wsjava_signaling_pbsws_MessageObject_descriptor,
        new java.lang.String[] { "DataType", "ListData", "StringDataObject", "StringData", "Log", "TimeStamp", });
    internal_static_wsjava_signaling_pbsws_StringDataObject_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wsjava_signaling_pbsws_StringDataObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wsjava_signaling_pbsws_StringDataObject_descriptor,
        new java.lang.String[] { "From", "To", "Offer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
